### ISSUE TITLE
Future proofing length

### ISSUE THREAD

**Issue by BrendanBenshoof** [jbenet/multihash#15]
Right now the multihash standard can only handle hash lengths of up to 255 bytes (2040 bits).

If we use a varint format to store the length of the hash, we can handle hashes of any lengths (essentially future-proofing the standard against increases in hash length)

using a "top bit = 1 -> more bytes follow && top bit = 0 -> last byte" approach means that all current hashes would still be valid despite the change in standard.

**Comment by jbenet** [comment]
It's already a varint



—

**Comment by BrendanBenshoof** [comment]
Ok, that is in the further discussion linked in the readme. (I should read more docs)

The example on the readme contradicts this (stating that it is 1-byte of length), while this is correct, it is not clear why it is the case beyond "just using 1 byte to encode length).
It might be worth explaining that in the readme.
