### ISSUE TITLE
Clojure implementation

### ISSUE THREAD

**Issue by greglook** [jbenet/multihash#2]
Hi @jbenet, I've implemented multihash in Clojure if you'd like to add it to the list in the README:
https://github.com/greglook/clj-multihash

The motivation was [another project of mine](/greglook/vault) which shares some ideas with IPFS. After reading through the spec and learning more about it, I think I may just drop the blob layer and use IPFS instead. :)

**Comment by jbenet** [comment]
@greglook happy to! could you send a PR adding it? 

and great! you can use the ipfs cli or http apis to use it directly from clj. be warned it's not perfect yet-- but getting there fast. drop by on irc for help with anything

**Comment by jbenet** [comment]
closed via #3
