### ISSUE TITLE
Examples are incorrect/incorrectly labeled

### ISSUE THREAD

**Issue by abrosen** [jbenet/multihash#9]
QmRJzsvyCQyizr73Gmms8ZRtvNxmgqumxc2KUp71dfEmoj # sha256 in base58

That's the base58 hash of "foo"  not "sha256"
Perhaps the intention was it's a sha256 hash of "foo" in base58.

**Comment by jbenet** [comment]
It's a sha256 hash encoded in base58. That's precisely what the comment says.

base58 is not a hash. It's an encoding.
